name: Test Squid Proxy Setup

on:
  workflow_dispatch:

jobs:
  test-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Network Restrictions
        run: |
          # Install and configure Squid proxy
          sudo apt-get update && sudo apt-get install -y squid
          
          # Create whitelist
          cat > /tmp/whitelist.txt << 'EOF'
          .anthropic.com
          .github.com
          .githubusercontent.com
          EOF
          
          # Configure Squid
          sudo tee /etc/squid/squid.conf << 'EOF'
          http_port 127.0.0.1:3128
          acl whitelist dstdomain "/tmp/whitelist.txt"
          acl localhost src 127.0.0.1/32
          http_access allow localhost whitelist
          http_access deny all
          cache deny all
          EOF
          
          # Stop any existing squid instance and start with our config
          sudo squid -k shutdown || true
          sleep 2
          sudo rm -f /run/squid.pid
          sudo squid -N -d 1 &
          sleep 5
          
          # Note: We cannot use iptables to block all HTTPS traffic in GitHub Actions
          # as it would block the runner's communication with GitHub
          # The proxy alone will handle the filtering
          
          # Set proxy environment variables
          echo "http_proxy=http://127.0.0.1:3128" >> $GITHUB_ENV
          echo "https_proxy=http://127.0.0.1:3128" >> $GITHUB_ENV
          echo "HTTP_PROXY=http://127.0.0.1:3128" >> $GITHUB_ENV
          echo "HTTPS_PROXY=http://127.0.0.1:3128" >> $GITHUB_ENV
      
      - name: Test Network Restrictions
        run: |
          echo "Testing whitelisted domains (should work):"
          curl -I https://api.github.com || echo "GitHub API failed"
          
          echo -e "\nTesting blocked domains (should fail):"
          curl -I -m 5 https://google.com || echo "Google blocked as expected"
          curl -I -m 5 https://example.com || echo "Example.com blocked as expected"
          
          echo -e "\nTesting direct IP (should fail):"
          curl -I -m 5 https://142.250.80.46 || echo "Direct IP blocked as expected"
          
          echo -e "\nChecking Squid logs:"
          sudo tail -20 /var/log/squid/access.log